### PR TITLE
Fix VcsSim lognames API

### PR DESCRIPTION
**Pull request by ZenithalHourlyRate**
This API was introduced by c9f43c165
"Test daisy chained homogeneous spike instances. (#334)" where multiple logs were needed.

However, this API was not implemented for `VcsSim`
so verilated rocket chip wont run, which will complain

    File riscv-tests/debug/testlib.py, line 1145, in run
      self.classSetup()
    File riscv-tests/debug/testlib.py, line 1199, in classSetup
      BaseTest.classSetup(self)
    File riscv-tests/debug/testlib.py, line 1110, in classSetup
      self.logs += self.target_process.lognames
    AttributeError: 'VcsSim' object has no attribute 'lognames'
    
This is related to https://github.com/chipsalliance/playground/pull/46

### CODE REVIEW

**Comment by jerryz123** [comment]
I didn't see this when I made #440. This can be closed now

**Comment by aswaterman** [comment]
Ah, indeed.
